package com.myapplication.finalproject.featureLocation.di

import com.myapplication.finalproject.ComponentForMissCircularDependency.ProviderGetCharacter

interface DependencyProviderCharacterForLocation:ProviderGetCharacter