package com.myapplication.finalproject.featureEpisodes.di

import com.myapplication.finalproject.ComponentForMissCircularDependency.ProviderGetCharacter

interface DependencyProviderGetCharactersForEpisodes:ProviderGetCharacter {
}